import type { Metadata } from "next";
import "../styles/globals.scss";
import { Geist} from "next/font/google"

//import { Geist, Geist_Mono } from "next/font/google";
//import {  Poppins  } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});



//const poppins =  Poppins({
//  subsets: ["latin"],
//  weight: ['400', '700']
//})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
